singleuser:
  image:
    name: ooidatateam/pangeo-notebook
    tag: 39cfe67
  cmd: ['start-singleuser.sh']
  memory:
    guarantee: 16G
  nodeSelector:
    cloud.google.com/gke-nodepool: notebook-highmem
  storage:
    capacity: 100Gi

hub:
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  extraConfig: |
    c.KubeSpawner.singleuser_service_account = 'daskkubernetes'
    c.KubeSpawner.start_timeout = 60 * 10 # 10-minute timeout for Azure
    c.Spawner.default_url = '/lab'
    c.Spawner.cmd = ['jupyter-labhub']
    from kubernetes import client
    def modify_pod_hook(spawner, pod):
        pod.spec.containers[0].security_context = client.V1SecurityContext(
            privileged=True,
            capabilities=client.V1Capabilities(
                add=['SYS_ADMIN']
            )
        )
        return pod
    c.KubeSpawner.modify_pod_hook = modify_pod_hook
    c.KubeSpawner.environment = {}

proxy:
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool

prePuller:
  hook:
    enabled: false

cull:
  enabled: true
  users: false
  timeout: 1200
  every: 600
