proxy:
  secretToken: SECRET
  https:
    enabled: true
    hosts:
      - "ooidataworkshops.net"
    type: letsencrypt
    letsencrypt:
      contactEmail: "tjcrone@gmail.com"
  service:
    loadBalancerIP: 104.154.228.108

auth:
  type: github
  github:
    clientId: ID
    clientSecret: SECRET
    callbackUrl: "https://ooidataworkshops.net/hub/oauth_callback"
  admin:
    access: true
    users:
      - tjcrone
      - friedrichknuth
      - seagrinch
      - mvardaro
